import type { Metadata } from "next";
import { Geist, Geist_Mono, Overpass } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import HeroSection from "@/Components/HeroSection";

// Import Overpass font
const overpass = Overpass({ subsets: ["latin"], weight: ["400", "700"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${overpass.className} antialiased`}
      >
        <div className="bg-[hsl(356,100%,66%)] text-white rounded-bl-[80px] min-h-[70vh] md:min-h-[50vh] lg:min-h-[60vh] xl:min-h-[80vh]">
          <Header />
          <HeroSection />
        </div>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
